name: CodeSonar
on:
  push:                  # Only run onces the Pull request is created
    branches:
      - 'release/**'               # Feature Branches
  pull_request:
    branches:
      - 'release/**'       
  
jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: codesecure-runner-set
    container:
      image: ghcr.io/codesecure-se/rust-cso-builder:8.2p0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      CAFILE: ".github/github.cert.pem" 
      TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      API_URL: https://api.github.com
      REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ROOT_TREE: "OSS-Projects/ripgrep-GitHub" 
      PROJECT_NAME: "ripgrep"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      CSONAR_HUB_URL: "https://partnerdemo.codesonar.com" 
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASSWORD }}"
      CSONAR_CSHOME: /opt/codesonar
      CS_USER_HOME: /__w/ripgrep/ripgrep
      COMMIT_HASH: ${{ github.sha }}
      REPO_URL: "https://github.com/CodeSecure-SE/ripgrep"    # the github.repositoryUrl is not an http-link.
      TARGET: ${{ github.base_ref }}
      IS_PR: ${{ github.event_name }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Safe directory
        run: git config --global --add safe.directory `pwd`
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          ref: main
          path: cso-scripts
      - name: Build and Analyze
        run: | 
           mv /home/user/.cargo /github/home/.cargo
           mv /home/user/.rustup /github/home/.rustup
           source /github/home/.cargo/env
           cargo clippy --no-deps --message-format=json | clippy-sarif > codesonar-scan.sarif
           python3 cso-scripts/build_and_analyze.py codesonar.conf codesonar import_sarif.py codesonar-scan.sarif -include-sources '**/*.rs'
        shell: bash
#      - name: Upload SARIF to GitHub #Use this if you do not have GitHub Enterprise
#        if: ${{ github.event.pull_request }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: SARIF file
#          path: warnings.sarif
      - name: Push Summary Report
        if: ${{ github.event.pull_request }}
        uses: thollander/actions-comment-pull-request@v2
        with: 
          filePath: warnings.md
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: warnings.sarif
          category: "CodeSecure CodeSonar"            
